before_script:
  - docker info

build_image:
  script:
    - docker login --username=auto@sun-person -p Lingshengauto1  registry.cn-hangzhou.aliyuncs.com
    - docker run --rm --net=host -v $PWD:/frontend -v $PWD/docker-entrypoint.sh:/docker-entrypoint.sh registry.cn-hangzhou.aliyuncs.com/sun-docker/frontend-builder:latest
    - docker build -t registry.cn-hangzhou.aliyuncs.com/lingsheng/verbal-trick:$CI_COMMIT_REF_NAME .
    - docker push registry.cn-hangzhou.aliyuncs.com/lingsheng/verbal-trick:$CI_COMMIT_REF_NAME
    - docker rmi registry.cn-hangzhou.aliyuncs.com/lingsheng/verbal-trick:$CI_COMMIT_REF_NAME
    
    # - docker login --username=auto@sun-person -p Lingshengauto1  registry.cn-hangzhou.aliyuncs.com
    # - docker push registry.cn-hangzhou.aliyuncs.com/lingsheng/lsrobot-vue:$CI_COMMIT_REF_NAME
    # - docker rmi registry.cn-hangzhou.aliyuncs.com/lingsheng/lsrobot-vue:$CI_COMMIT_REF_NAME